name: ldm
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit
  - pytorch
  - torchvision
  - numpy
  - pip:
    - albumentations
    - opencv-python
    - pudb
    - imageio
    - imageio-ffmpeg
    - pytorch-lightning
    - omegaconf
    - test-tube
    - streamlit
    - einops
    - tqdm
    - torch-fidelity
    - transformers
    - taming-transformers-rom1504
